@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlZ0ByZWcuY29tIiwiaWF0IjoxNzA0MTkyNjc1fQ.9jHVYUTHYN4lLKz4-gEwTny9i1bz6VLBNprgjOKJZaY


### caller gets all invites
GET http://localhost:8080/api/v1/userCaller/6592c9a7142366537e74c9da
Authorization: bearer {{token}}

### caller update invite
PATCH http://localhost:8080/api/v1/userCaller/65db367b40c6a48e7f35e19e/65f4986e9e00eaca02930090
Authorization: bearer {{token}}
Content-Type: application/json

{
    "isAccepted": true,
    "isDeclined": false,
    "isPending": false
}